### ISSUE TITLE
Tree-sitter Notebooks: linkify parsed result

### ISSUE THREAD

**Issue by TylerLeonhardt** [jrieken/vscode-tree-sitter-query#3]
I'd love to be able to click on these linked tokens and it causes a range in the code editor to show up
<img width="402" alt="image" src="https://github.com/jrieken/vscode-tree-sitter-query/assets/2644648/319a3aa1-3ed7-4563-9781-d45850612519">

**Comment by TylerLeonhardt** [comment]
cc @joyceerhl @rebornix

**Comment by ulugbekna** [comment]
Closed by https://github.com/jrieken/vscode-tree-sitter-query/pull/8
