### ISSUE TITLE
Tree-sitter Notebooks: doesn't include property names

### ISSUE THREAD

**Issue by TylerLeonhardt** [jrieken/vscode-tree-sitter-query#4]
<img width="380" alt="image" src="https://github.com/jrieken/vscode-tree-sitter-query/assets/2644648/5ae21275-646b-4397-98f3-d9619af901bb">
vs
<img width="474" alt="image" src="https://github.com/jrieken/vscode-tree-sitter-query/assets/2644648/6e8a21a4-c036-4790-9a41-e29f2bda4adc">

Notice `name:` and `body:` are not included.

**Comment by TylerLeonhardt** [comment]
cc @joyceerhl

**Comment by qcho** [comment]
For anyone wondering this is implemented now

<img width="609" alt="image" src="https://github.com/user-attachments/assets/e870a696-9a31-42f7-b6c1-b1a01bdde96e">
